AWSTemplateFormatVersion: 2010-09-09
Description: Creating an IAM User

Resources:
  MyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: Developer # give a name to this user
      LoginProfile: # specify a password for this user
        Password: Ralph123ael.
        PasswordResetRequired: true # make this user to set a new password on next sign-in
      Path: '/'
      Groups: # attach this user to the list of existing groups
          - testgroupA
          - testgroupB
      ManagedPolicyArns: # list of ARNs of IAM managed policies that you want to attach to the user
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess # provides administrator access to AWS 
      
SubnetId: !Ref PublicSubnet
      UserData:
         Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum update –y
            sudo yum install java-1.8.0-openjdk-devel -y
            curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
            sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
            sudo systemctl daemon-reload
            sudo amazon-linux-extras install epel -y
            sudo yum install jenkins -y
            sudo systemctl start jenkins
            sudo systemctl status jenkins
            sudo systemctl enable jenkins
            sudo cat /var/lib/jenkins/secrets/initialAdminPassword
